### PR TITLE
UX Improvements

### PR DESCRIPTION
**Pull request by jsimplicio**
Making some UX changes to Something Tracker :)

### CODE REVIEW

**Comment by jsimplicio** [comment]
So far I've separated the sign up and login forms because it was a little confusing that they were the same form.

Here's how it looks. You can toggle between them by clicking on 'Log in?' and 'Sign up?'

screen shot 2016-02-13 at 11 07 51 am
screen shot 2016-02-13 at 11 08 49 am

**Comment by gr2m** [comment]
A lot better than what we have right now already :+1: I think we could simplify the JS/CSS implementation a bit, but we can do that later. Maybe @nickcolley / @espy have any feedback for the work in progress?

**Comment by jsimplicio** [comment]
Also I can't get both Sign up and Log in forms to disappear once you are logged in. Sign up's form keeps coming back

**Comment by jsimplicio** [comment]
I also feel like instead of simply just clearing tracked items list you should be able to delete one by one if you wanted to? Pretty important action imo

**Comment by gr2m** [comment]
> I can't get both Sign up and Log in forms to disappear once you are logged in

One thing I like to do is to use `data-` attributes for that. It’s easier than adding / removing classes like `.signed-in` / `.signed-out`, because it can only have one property at a time, so setting it replaces the current value.

So on page load, I’d check `if (account.isSignedIn())` and then set `<html data-account-state="signed-in">` or `<html data-account-state="signed-out">` accordingly. Then you use that to toggle parts of the site, e.g.

```js
.account-forms,
.signedin-message {
  display: none
}
[data-account-state=signed-out] .account-forms {
  display: block
}
[data-account-state=signed-in] .signedin-message {
  display: block
}
```

That way you don’t need to toggle classes at many places to differentiate between signed in / out states, but only change one property. For the above example, you’d need to wrap the two forms into an extra div with `account-forms` class

> I also feel like instead of simply just clearing tracked items list you should be able to delete one by one if you wanted to? Pretty important action imo

I agree :+1:

**Comment by jsimplicio** [comment]
Got it. How do I make it so 'isSignedIn()' points to the data attribute of signed in? Sorry don't know enough JS :panda_face:

**Comment by nickcolley** [comment]
Sorry I haven't had a chance to properly look at this yet, just wanted to say this is great.

Only thing from glancing is the use of utilities classes with short selector names might be confusing to newcomers, so if it were possible to do it without that'd be great.

To extend @gr2m 's thought on using data- attributes for styling you could do something more generic like `visible-if-signed-in` `hidden-if-signed-in`, this'd allow you to do the same thing declaratively.

**Comment by jsimplicio** [comment]
how do I make `isSignedIn()` point to `data-account-state` ?

**Comment by gr2m** [comment]
```js
if (hoodie.account.isSignedIn()) {
  document.body.setAttribute('data-account-state', 'signed-in')
} else {
  document.body.setAttribute('data-account-state', 'signed-out')
}
```

This will the `data-account-state` attribute on the `<body>` element

**Comment by jsimplicio** [comment]
Hmm, I did that and when you sign in it `data-account-stage` doesn't register at `signed-in` automatically, only if you reload the page. So the Hello message doesn't show until you reload and it recognizes you're signed in

**Comment by jsimplicio** [comment]
Also on clicking on sign out the console gives you this error `signOutbundle.js:2639TypeError: undefined is not an object (evaluating 'state.account.session')`

**Comment by jsimplicio** [comment]
And the action to clear the table also seems to not be working correctly. Page doesn't refresh, and doesn't clear automatically.

**Comment by gr2m** [comment]
@jsimplicio can you run `npm update` so you get the latest version of everything? There are still a few known issues in the current Hoodie version, but the signout should work. Maybe let’s pair on this?

**Comment by gr2m** [comment]
great work so far, much better than what we have right now. Looking forward to see more improvements :)

**Comment by gr2m** [comment]
merged via 8c4e726

**Pull request closed without merging**
